name: Generate Snake Animation
on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-snake:
    name: Generate and Update Snake Animation
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Necessary to push to the repository
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main  # Explicitly checkout main branch
          persist-credentials: true  # Important for pushing later

      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          show_private: true
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create output branch
        run: |
          git checkout --orphan output
          git reset --hard
          git rm -rf .

      - name: Commit and push
        run: |
          mkdir -p dist
          cp dist/github-contribution-grid-snake.svg .
          cp dist/github-contribution-grid-snake.gif .
          git add .
          git commit -m "Update snake animation - $(date)"
          git push origin output --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}