name: Generate Snake Animation
on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-snake:
    name: Generate and Update Snake Animation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Generate full snake
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: snake.svg
          gif_out_path: snake.gif

      # Highlight 2024 contributions
      - name: Highlight Current Year Contributions
        run: |
          sudo apt-get update -y
          sudo apt-get install -y xmlstarlet
          
          # Make non-2024 contributions very light
          xmlstarlet ed \
            -u "//svg:rect[not(contains(@data-date, '2024'))]/@fill" \
            -v "#ebedf0" \
            snake.svg > highlighted-snake.svg
          
          # Make 2024 contributions stand out
          xmlstarlet ed \
            -u "//svg:rect[contains(@data-date, '2024') and contains(@fill, '#c6e48b')]/@fill" \
            -v "#40c463" \
            highlighted-snake.svg > final-snake.svg
          
          mv final-snake.svg snake.svg

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Prepare Output Branch
        run: |
          # Store snake files temporarily
          mkdir -p ../snake-temp
          cp snake.svg ../snake-temp/
          cp snake.gif ../snake-temp/
          
          # Check if output branch exists
          if git ls-remote --exit-code --heads origin output; then
            git fetch origin output
            git checkout -f output
            git rm -f snake.svg snake.gif || true
          else
            git checkout --orphan output
            git commit --allow-empty -m "Initial commit"
          fi
          
          # Restore snake files
          mv ../snake-temp/snake.svg .
          mv ../snake-temp/snake.gif .

      - name: Commit and Push
        run: |
          git add .
          git commit -m "Update snake animation - $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}