name: Generate Snake Animation
on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-snake:
    name: Generate and Update Snake Animation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: main-repo

      # Create working directories
      - name: Setup directories
        run: |
          mkdir -p main-repo/temp
          mkdir -p main-repo/dist
        working-directory: .

      # Generate full snake in temporary location
      - name: Generate Full Snake
        uses: Platane/snk@master
        id: full-snake
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: main-repo/temp/full-snake.svg
          gif_out_path: main-repo/temp/full-snake.gif

      # Filter to show only 2024 contributions
      - name: Filter 2024 Contributions
        run: |
          sudo apt-get update -y
          sudo apt-get install -y xmlstarlet
          
          # Process SVG to gray out pre-2024 contributions
          xmlstarlet ed \
            -u "//svg:rect[contains(@data-date, '2023') or contains(@data-date, '2022') or contains(@data-date, '2021') or contains(@data-date, '2020')]/@fill" \
            -v "#ebedf0" \
            main-repo/temp/full-snake.svg > main-repo/dist/github-contribution-grid-snake.svg
          
          # Copy GIF
          cp main-repo/temp/full-snake.gif main-repo/dist/github-contribution-grid-snake.gif
        working-directory: .

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
        working-directory: ./main-repo

      - name: Prepare Output Branch
        run: |
          # Check if output branch exists
          if git ls-remote --exit-code --heads origin output; then
            git fetch origin output
            git checkout output
            git reset --hard origin/output
          else
            git checkout --orphan output
            git commit --allow-empty -m "Initial commit"
          fi
          
          # Clean working directory except dist
          find . -mindepth 1 -maxdepth 1 ! -name dist -exec rm -rf {} + || true
        working-directory: ./main-repo

      - name: Commit and Push
        run: |
          # Move files to root
          mv dist/github-contribution-grid-snake.svg .
          mv dist/github-contribution-grid-snake.gif .
          
          # Commit and push
          git add .
          git commit -m "Update 2024 snake animation - $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin output
        working-directory: ./main-repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}