name: Generate Snake Animation
on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main  # Optional: run when pushing to main

jobs:
  generate-snake:
    name: Generate and Update Snake Animation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      # Generate snake animation (including private contributions)
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif  # Optional GIF version

      # Deploy to output branch
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
          jekyll: false  # Disable Jekyll processing
        env:
          GITHUB_TOKEN: ${{ secrets.SNAKE }}  # Use default token